language: node_js
sudo: false
node_js:
  - "0.12"
env:
  - UNDERSCORE=1.4.4 BACKBONE=1.0 MARIONETTE=2.1
  - UNDERSCORE=1.6 BACKBONE=1.1 MARIONETTE=2.2
  - UNDERSCORE=1.8 BACKBONE=1.2 MARIONETTE=2.4
  - LODASH=2.4 BACKBONE=1.0 MARIONETTE=2.1
  - LODASH=3.0 BACKBONE=1.1 MARIONETTE=2.2
  - LODASH=3.1 BACKBONE=1.2 MARIONETTE=2.4
install:
  - curl -L https://rawgit.com/Squareknot/marionette.state/master/travis-matrix-install | bash
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
