#!/bin/bash
npm install
npm dedupe

echo "Overriding underscore with v$UNDERSCORE"

if [[ -n "$UNDERSCORE" ]]; then
  npm install underscore@"$UNDERSCORE"
fi

echo "Overriding backbone with v$BACKBONE"

if [[ -n "$BACKBONE" ]]; then
  npm install backbone@"$BACKBONE"
fi

echo "Overriding backbone.marionette with v$MARIONETTE"

if [[ -n "$MARIONETTE" ]]; then
  npm install backbone.marionette@"$MARIONETTE"
fi

if [[ -n "$LODASH" ]]; then
  echo "Overriding underscore with lodash v$LODASH"

  npm install lodash@"$LODASH"

  # Lodash@2 and Lodash@3 have different file structures
  if [[ "$LODASH" < "3.0" ]]
  then
    mv node_modules/lodash/lodash.js node_modules/underscore/underscore.js
  else 
    mv node_modules/lodash/index.js node_modules/underscore/underscore.js
  fi
fi
